"""Render docs/compliance_matrix.md from docs/requirements.yaml and docs/compliance.yaml.

compliance.yaml maps a requirement id (or an id prefix ending in '*') to {path, artifact, status, note}.
Status values: pass, fail, partial, deviation, n/a, planned.
"""

from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]


def main() -> None:
    reqs = yaml.safe_load((ROOT / "docs/requirements.yaml").read_text())
    mapping_path = ROOT / "docs/compliance.yaml"
    mapping = yaml.safe_load(mapping_path.read_text()) if mapping_path.exists() else {}
    mapping = mapping or {}

    def lookup(rid: str) -> dict:
        if rid in mapping:
            return mapping[rid]
        best = None
        for key, val in mapping.items():
            if key.endswith("*") and rid.startswith(key[:-1]) and (best is None or len(key) > len(best[0])):
                best = (key, val)
        return best[1] if best else {}

    counts: dict[str, int] = {}
    rows = []
    for r in reqs:
        m = lookup(r["id"])
        status = m.get("status", "planned")
        counts[status] = counts.get(status, 0) + 1
        req = r["requirement"].replace("|", "/")
        note = str(m.get("note", "")).replace("|", "/")
        rows.append(f"| {r['id']} | {req} | {m.get('path', '')} | {m.get('artifact', '')} | {status} | {note} |")

    summary = ", ".join(f"{k}: {v}" for k, v in sorted(counts.items()))
    lines = [
        "# Compliance matrix",
        "",
        "Generated by `scripts/make_compliance_matrix.py` from `docs/requirements.yaml` (one row per atomic requirement "
        "of the brief) and `docs/compliance.yaml`. Do not edit by hand.",
        "",
        f"Status counts: {summary}.",
        "",
        "| Id | Requirement | File path | Artifact | Status | Note |",
        "|---|---|---|---|---|---|",
        *rows,
        "",
    ]
    (ROOT / "docs/compliance_matrix.md").write_text("\n".join(lines))
    print(f"wrote docs/compliance_matrix.md ({len(rows)} rows; {summary})")


if __name__ == "__main__":
    main()
