"""Writes benchmark_report.md, metrics.json and gates.json from a scored benchmark (runner.score_runs)."""

from __future__ import annotations

import json
import logging
import math
from collections import defaultdict
from pathlib import Path
from typing import Any

import numpy as np

from scan2scope.bench.gates import _display_path
from scan2scope.types import TIERS

log = logging.getLogger("scan2scope.bench")

STAGES = ("ingest", "geometry", "layout", "stitch", "semantics", "rules", "uncertainty", "scope")
AREA_GATES = ("floor_area", "footprint", "damage_area")  # worst items in m2, all others in cm

GATES_NOTE = ("Status per tier against `bench/gates.yaml`. `assumed` marks thresholds the brief does not "
              "state. A missing value (room, wall or opening not found, capture failed) counts as a failing "
              "item.")
RANK_NOTE = ("Score: worst error over its allowance minus 1 for error gates, relative gap to the target for "
             "rate gates, miss rate over the nominal miss rate minus 1 for calibration, the count for "
             "confident garbage, failing share for checks.")
CEILING_NOTE = ("Accuracy against the tape or laser reading and spread across repeat captures are scored "
                "separately; the mode names which of the two fails.")
REPEAT_NOTE = ("Rooms and walls are matched through the ground truth. Allowed |delta| is max(1 cm, 0.5% of "
               "the GT length); the strict reading is min(1 cm, 0.5%).")
CAL_NOTE = ("Coverage of the 90% intervals over every scored value, with an exact (Clopper-Pearson) 95% "
            "interval. Rooms counts distinct physical rooms; repeat captures of a room share one unit. With "
            "fewer than 9 rooms a tier keeps its prior interval multiplier and its coverage interval is too "
            "wide to show calibration. Confident garbage is a miss by more than the configured multiple of "
            "the half-width.")
DETECT_NOTE = ("Openings match on the same matched wall, compatible type (door and open passage are "
               "interchangeable) and centre within half the GT width. Phantoms in rooms that match no GT "
               "room are scored only when the capture covers the whole property.")
ABLATION_NOTE = ("The same capture run with drift correction on and with it off (`<capture>__nodrift`). Gain "
                 "is how much the correction reduced the error (positive is better).")
H2H_MISSING = ("No magicplan export found (bench/data/<property>/magicplan/statistics.csv and "
               "dimensions.yaml).")
H2H_RULE = ("Beat or tie: |ours - gt| <= |theirs - gt| + 3 mm for lengths, our relative error within 0.2 "
            "percentage points of theirs for areas. A dimension magicplan reports in a room our capture "
            "covers but that we did not report counts as a loss.")
SYNTH_NOTE = ("are generated by scan2scope.synth with exact ground truth. Tiers marked (synthetic) are "
              "scored only on such captures, and no real phone produced them.")


def jsonable(x: Any) -> Any:
    """JSON-safe copy: numpy to Python, non-finite floats to None, tuples and sets to lists, paths to str."""
    if x is None or isinstance(x, (str, bool)):
        return x
    if isinstance(x, np.bool_):
        return bool(x)
    if isinstance(x, (int, np.integer)):
        return int(x)
    if isinstance(x, (float, np.floating)):
        return float(x) if math.isfinite(float(x)) else None
    if isinstance(x, dict):
        return {str(k): jsonable(v) for k, v in x.items()}
    if isinstance(x, (list, tuple)):
        return [jsonable(v) for v in x]
    if isinstance(x, (set, frozenset)):
        return sorted((jsonable(v) for v in x), key=str)
    if isinstance(x, np.ndarray):
        return jsonable(x.tolist())
    return str(x)


def _esc(s: Any) -> str:
    return str(s).replace("|", "\\|").replace("\n", " ")


def _table(header: list[str], rows: list[list[Any]]) -> list[str]:
    out = ["| " + " | ".join(_esc(h) for h in header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(_esc(c) for c in r) + " |" for r in rows]
    return out


def _m(x: float | None, nd: int = 3) -> str:
    return "" if x is None else f"{x:.{nd}f}"


def _cm(x: float | None, signed: bool = False) -> str:
    if x is None:
        return ""
    return f"{100 * x:+.1f} cm" if signed else f"{100 * x:.1f} cm"


def _m2(x: float | None, signed: bool = False) -> str:
    if x is None:
        return ""
    return f"{x:+.2f} m2" if signed else f"{x:.2f} m2"


def _pct(x: float | None, signed: bool = False) -> str:
    if x is None or not math.isfinite(x):
        return ""
    return f"{100 * x:+.1f}%" if signed else f"{100 * x:.1f}%"


def _yes(b: Any) -> str:
    return "yes" if b else "no"


def _status(s: str) -> str:
    return {"pass": "PASS", "fail": "FAIL"}.get(s, s)


def _tier_name(tier: str, synthetic: str) -> str:
    return {"all": f"{tier} (synthetic)", "some": f"{tier} (partly synthetic)"}.get(synthetic, tier)


def _cap(m: dict[str, Any]) -> str:
    """property/capture, with __nodrift for the ablation run."""
    return f"{m['property']}/{m['capture']}" + ("__nodrift" if m.get("variant") == "nodrift" else "")


def _worst_text(row: dict[str, Any]) -> str:
    size = _m2 if row.get("gate") in AREA_GATES else _cm
    parts = []
    for w in row.get("worst") or []:
        where = f"{w.get('property') or '?'}/{w.get('capture') or '?'}/{w.get('item')}"
        if w.get("detail"):
            parts.append(w["detail"])
        elif w.get("reason"):
            parts.append(f"{where} ({w['reason']})")
        elif w.get("err") is not None and w.get("allowed") is not None:
            parts.append(f"{where} err {size(w['err'], True)} (allowed {size(w['allowed'])})")
        elif w.get("miss_ratio") is not None:
            parts.append(f"{where} {w['kind']} gt {_m(w['gt'])} interval [{_m(w['lo'])}, {_m(w['hi'])}]")
        elif w.get("ours_err") is not None:
            parts.append(f"{w.get('item')} ({w.get('capture')}): ours {_cm(w['ours_err'], True)}, "
                         f"theirs {_cm(w['theirs_err'], True)}")
        else:
            parts.append(where)
    return "; ".join(parts)


def _gate_section(bench: dict[str, Any]) -> list[str]:
    rows = bench["gates"]["rows"]
    out = ["## Gate summary", "", GATES_NOTE, ""]
    for tier in [t for t in TIERS if any(r["tier"] == t for r in rows)]:
        trows = [r for r in rows if r["tier"] == tier]
        out += [f"### {_tier_name(tier, trows[0].get('synthetic', 'none'))}", ""]
        out += _table(["Gate", "Status", "Measured", "Threshold", "n", "Pass share", "Assumed"],
                      [[r["gate"], _status(r["status"]), r["measured_text"], r["threshold"], r["n"],
                        _pct(r["pass_share"]), "assumed" if r["assumed"] else ""] for r in trows])
        fails = [r for r in trows if r["status"] == "fail" and r.get("worst")]
        if fails:
            out += ["", "Worst items:", ""]
            out += [f"- {r['gate']}: {_worst_text(r)}" for r in fails]
        out.append("")
    ranked = bench["gates"]["ranked_failures"]
    out += ["## Failing gates ranked for the fix loop", ""]
    if ranked:
        out += [RANK_NOTE, ""]
        out += _table(["Rank", "Tier", "Gate", "Score", "Measured", "Threshold"],
                      [[k + 1, r["tier"], r["gate"], f"{r['score']:.2f}", r["measured_text"], r["threshold"]]
                       for k, r in enumerate(ranked)])
    else:
        out.append("No failing gates.")
    out.append("")
    return out


def _ceiling_section(bench: dict[str, Any]) -> list[str]:
    rows = {(r["tier"], r["gate"]): r for r in bench["gates"]["rows"]}
    modes = bench["gates"].get("ceiling_mode", {})
    if not modes:
        return []
    out = ["## Ceiling height: bias or spread", "", CEILING_NOTE, ""]
    body = []
    for tier in [t for t in TIERS if t in modes]:
        acc, sp = rows.get((tier, "ceiling_height")), rows.get((tier, "ceiling_spread"))
        bias = _bias(bench["metrics"], tier)
        body.append([tier, _status(acc["status"]) if acc else "", acc["measured_text"] if acc else "",
                     "" if bias is None else _cm(bias, True), _status(sp["status"]) if sp else "",
                     sp["measured_text"] if sp else "", modes[tier]])
    out += _table(["Tier", "Accuracy", "Accuracy detail", "Mean signed error", "Spread", "Spread detail",
                   "Mode"], body)
    out.append("")
    return out


def _bias(metrics: list[dict[str, Any]], tier: str) -> float | None:
    errs = [r["err"] for m in metrics if m["tier"] == tier for r in m["records"]
            if r["kind"] == "ceiling_height"]
    return sum(errs) / len(errs) if errs else None


def _repeat_section(bench: dict[str, Any]) -> list[str]:
    rep = bench["repeatability"]
    out = ["## Repeatability", ""]
    if not rep["walls"] and not rep["ceiling"]:
        out += ["No room was scored in two captures of the same tier.", ""]
        return out
    out += [REPEAT_NOTE, ""]
    out += _table(["Property", "Tier", "Room", "Wall", "Captures", "Values (m)", "|delta|", "Allowed", "Pass",
                   "Strict allowed", "Strict pass"],
                  [[w["property"], w["tier"], w["room"], w["wall"], " vs ".join(w["captures"]),
                    " / ".join(_m(v) for v in w["values"]), _cm(w["delta"]), _cm(w["allowed"]),
                    _yes(w["pass"]), _cm(w["strict_allowed"]), _yes(w["strict_pass"])]
                   for w in rep["walls"]])
    if rep["ceiling"]:
        out += ["", "Ceiling height across captures:", ""]
        out += _table(["Property", "Tier", "Room", "Captures", "Values (m)", "Spread"],
                      [[c["property"], c["tier"], c["room"], ", ".join(c["captures"]),
                        " / ".join(_m(v) for v in c["values"]), _cm(c["spread"])] for c in rep["ceiling"]])
    if rep["structure"]:
        out += ["", "Same plan structure (walls and openings found in both captures):", ""]
        out += _table(["Property", "Tier", "Room", "Captures", "Walls", "Openings", "Same walls",
                       "Same openings"],
                      [[s["property"], s["tier"], s["room"], " vs ".join(s["captures"]),
                        " / ".join(str(v) for v in s["n_walls"]), " / ".join(str(v) for v in s["n_openings"]),
                        _yes(s["same_walls"]), _yes(s["same_openings"])] for s in rep["structure"]])
    out.append("")
    return out


def _calibration_section(bench: dict[str, Any]) -> list[str]:
    cal = bench["gates"]["calibration"]
    out = ["## Calibration", ""]
    if not cal:
        out += ["No scored values.", ""]
        return out
    q_status = defaultdict(set)
    for m in bench["metrics"]:
        if m.get("calibration_status"):
            q_status[m["tier"]].add(f"{m['calibration_status']}" + (f" q={m['q']:g}" if m.get("q") else ""))
    order = sorted(cal.items(), key=lambda kv: TIERS.index(kv[0]) if kv[0] in TIERS else len(TIERS))
    out += [CAL_NOTE, ""]
    out += _table(["Tier", "Values", "Rooms", "Covered", "Coverage", "95% CI", "Contains 0.90",
                   "Mean half-width (% of GT)", "Confident garbage", "Interval multiplier"],
                  [[t, c["n"], c["rooms"], c["covered"], _pct(c["coverage"]),
                    f"[{_pct(c['ci'][0])}, {_pct(c['ci'][1])}]", _yes(c["contains_nominal"]),
                    _pct(c.get("mean_rel_half_width")), c["confident_garbage"],
                    ", ".join(sorted(q_status.get(t, [])))] for t, c in order])
    out += ["", "By kind (half-widths and errors in metres, or square metres for areas):", ""]
    out += _table(["Tier", "Kind", "n", "Coverage", "Mean half-width", "Mean |err|"],
                  [[t, k, v["n"], _pct(v["coverage"]), _m(v["mean_half_width"]), _m(v["mean_abs_err"])]
                   for t, c in order for k, v in c["by_kind"].items()])
    out.append("")
    return out


def _detection_section(bench: dict[str, Any]) -> list[str]:
    ms = bench["metrics"]
    out = ["## Rooms, openings and damage", "", DETECT_NOTE, ""]
    out += _table(["Capture", "Tier", "Status", "GT rooms", "Predicted", "Matched", "Missed rooms",
                   "Extra rooms", "Adjacency", "Max overlap (m2)"],
                  [[_cap(m), m["tier"], m["status"], m["rooms"]["gt"], m["rooms"]["pred"],
                    m["rooms"]["matched"], ", ".join(m["rooms"]["missed"]), ", ".join(m["rooms"]["extra"]),
                    _adj_text(m.get("adjacency")), _m((m.get("overlap") or {}).get("max_m2"))] for m in ms])
    out += ["", "Openings:", ""]
    out += _table(["Capture", "Tier", "GT", "Matched", "Missed", "Phantom", "Door/passage swaps",
                   "Unscored phantoms"],
                  [[_cap(m), m["tier"], m["openings"]["gt"], m["openings"]["matched"],
                    m["openings"]["missed"], m["openings"]["phantom"], m["openings"]["type_swaps"],
                    m["openings"]["phantom_unscored"]] for m in ms])
    if any(m["damage"]["gt"] or m["damage"]["phantom"] or m["damage"]["matched"] for m in ms):
        out += ["", "Damage (staged damage is disclosed as staged in the ground truth):", ""]
        out += _table(["Capture", "Tier", "GT regions", "Matched", "Class correct", "Missed", "Phantom"],
                      [[_cap(m), m["tier"], m["damage"]["gt"], m["damage"]["matched"],
                        m["damage"]["class_ok"], m["damage"]["missed"], m["damage"]["phantom"]] for m in ms])
    out.append("")
    return out


def _adj_text(a: dict[str, Any] | None) -> str:
    if not a:
        return ""
    if a.get("exact") is None:
        return "GT adjacency unknown"
    if a["exact"]:
        return f"exact ({len(a['gt'])} pair{'' if len(a['gt']) == 1 else 's'})"
    parts = [f"{len(a['correct'])}/{len(a['gt'])} correct"]
    if a["missing"]:
        parts.append("missing " + ", ".join("-".join(p) for p in a["missing"]))
    if a["extra"]:
        parts.append("extra " + ", ".join("-".join(p) for p in a["extra"]))
    if a["unmatched_rooms"]:
        parts.append(f"{len(a['unmatched_rooms'])} with unmatched rooms")
    return "; ".join(parts)


def _ablation_section(bench: dict[str, Any]) -> list[str]:
    entries = (bench.get("ablation") or {}).get("entries", [])
    out = ["## Drift ablation", ""]
    if not entries:
        out += ["No multi-room video or LiDAR capture has both runs.", ""]
        return out
    out += [ABLATION_NOTE, ""]
    rows = []
    for e in entries:
        on, off = e["on"], e["off"]
        name = f"{e['property']}/{e['capture']}" + (" (synthetic)" if e.get("synthetic") else "")
        rows.append([name, e["tier"], _m(on["footprint_gt"], 2),
                     f"{_m(on['footprint_pred'], 2)} ({_pct(on['footprint_rel_err'], True)})",
                     f"{_m(off['footprint_pred'], 2)} ({_pct(off['footprint_rel_err'], True)})",
                     _pct(e["footprint_gain"]),
                     f"{_cm(on['walls']['mean_abs_err'])} / {_cm(off['walls']['mean_abs_err'])}",
                     f"{_cm(on['walls']['max_abs_err'])} / {_cm(off['walls']['max_abs_err'])}",
                     f"{_pct(on['walls']['pass_share'])} / {_pct(off['walls']['pass_share'])}",
                     _drift_text(on.get("drift"))])
    out += _table(["Capture", "Tier", "Footprint GT (m2)", "On", "Off", "Footprint gain",
                   "Wall mean |err| on / off", "Wall max |err| on / off", "Walls in tolerance on / off",
                   "Drift record (on)"], rows)
    out.append("")
    return out


def _drift_text(d: Any) -> str:
    if not isinstance(d, dict):
        return "none"
    parts = [f"enabled={d.get('enabled')}"]
    loop = d.get("loop_closure")
    if isinstance(loop, dict) and "accepted" in loop:
        parts.append(f"loop closure {'accepted' if loop['accepted'] else 'rejected'}")
    for k, v in d.items():
        if k not in ("enabled", "loop_closure") and isinstance(v, (int, float)) and not isinstance(v, bool):
            parts.append(f"{k}={v:.3g}")
        if len(parts) >= 5:
            break
    return ", ".join(parts)


def _h2h_section(bench: dict[str, Any]) -> list[str]:
    h = bench.get("h2h")
    out = ["## Head-to-head against magicplan", ""]
    if not h:
        out += [H2H_MISSING, ""]
        return out
    for prop, info in h["by_property"].items():
        mapping = ", ".join(f"{k} = {v}" for k, v in (info.get("column_mapping") or {}).items() if v)
        columns = ", ".join(info.get("columns_found") or []) or "none"
        out.append(f"- {prop}: {info.get('app')} {info.get('version') or '(version not recorded)'}"
                   + (f", {info['mode']}" if info.get("mode") else "")
                   + f"; statistics.csv columns found: {columns}; used {mapping or 'none'}"
                   + (f"; flags {', '.join(info['flags'])}" if info.get("flags") else ""))
    out += ["", H2H_RULE, ""]
    for c in h["comparisons"]:
        title = f"{c['property']}/{c['capture']} ({c['tier']}): {c['beat_or_tie']}/{c['n']} beat or tie"
        out += [f"### {title} ({_pct(c['share'])})", ""]
        out += _table(["Room", "Dimension", "GT", "magicplan", "magicplan err", "Ours", "Our err",
                       "Beat or tie"],
                      [[d["room"], d["dimension"], _m(d["gt"]), _m(d["theirs"]), _err(d, "theirs_err"),
                        _m(d["ours"]), _err(d, "ours_err"), _yes(d["beat_or_tie"])] for d in c["dimensions"]])
        out.append("")
    return out


def _err(d: dict[str, Any], key: str) -> str:
    if d[key] is None:
        return "missing"
    if d["kind"] == "area":
        return _pct(d[key] / d["gt"], True)
    return _cm(d[key], True)


def _timing_section(bench: dict[str, Any]) -> list[str]:
    ms = [m for m in bench["metrics"] + bench.get("nodrift_metrics", []) if m.get("timing")]
    out = ["## Timing", ""]
    if not ms:
        out += ["No timing recorded.", ""]
        return out
    seen = {s for m in ms for s in (m["timing"].get("stages") or {})}
    stages = [*STAGES, *sorted(seen - set(STAGES))]
    used = [s for s in stages if any((m["timing"].get("stages") or {}).get(s) is not None for m in ms)]
    out += ["Seconds per pipeline stage from result.json, and the runner's wall time per capture.", ""]
    rows = []
    for m in ms:
        t = m["timing"]
        rows.append([_cap(m), m["tier"], _m(t.get("total_s"), 1),
                     *[_m((t.get("stages") or {}).get(s), 1) for s in used], _m(t.get("run_s"), 1)])
    out += _table(["Capture", "Tier", "Total", *used, "Runner"], rows)
    out.append("")
    return out


def _failures_section(bench: dict[str, Any]) -> list[str]:
    every = bench["metrics"] + bench.get("nodrift_metrics", [])
    bad = [m for m in every if m["status"] != "ok"]
    stage = [m for m in every if m["status"] == "ok" and m.get("stage_failures")]
    unreadable = bench.get("load_errors") or []
    out = ["## Failed or missing captures", ""]
    if not bad and not unreadable and not stage:
        out += ["None.", ""]
        return out
    out += [f"- ground truth {e['path']} could not be read, so none of its captures were scored: "
            f"{e['error']}" for e in unreadable]
    out += [f"- {_cap(m)} ({m['tier']}): {m['status']}" + (f": {m['error']}" if m.get("error") else "")
            for m in bad]
    out += [f"- {_cap(m)} ({m['tier']}): result written, but a stage failed: {', '.join(m['stage_failures'])}"
            for m in stage]
    out.append("")
    return out


def render(bench: dict[str, Any]) -> str:
    props = bench.get("properties", [])
    synth = [p["property"] for p in props if p.get("synthetic")]
    commits = sorted({c for c in bench.get("commits", []) if c})
    head = (f"Generated {bench.get('generated', '')} from `{_display_path(bench.get('data_root', ''))}` with gates from "
            f"`{bench['gates'].get('config') or 'bench/gates.yaml'}`. Pipeline commit(s) in the results: "
            f"{', '.join(c[:10] for c in commits) or 'not recorded'}. "
            f"Cache mode: {bench.get('cache_mode', '')}.")
    names = ", ".join(p["property"] for p in props) or "none"
    out = ["# Benchmark report", "", head, "",
           f"Properties: {names}; {len(bench['metrics'])} captures scored.", ""]
    if synth:
        out += [f"Synthetic captures: {', '.join(synth)} {SYNTH_NOTE}", ""]
    for section in (_gate_section, _ceiling_section, _repeat_section, _calibration_section,
                    _detection_section, _ablation_section, _h2h_section, _timing_section, _failures_section):
        out += section(bench)
    flags = [f"{p['property']}: {f}" for p in props for f in p.get("flags", [])]
    if flags:
        out += ["## Ground-truth flags", "", *[f"- {f}" for f in flags[:50]]]
        if len(flags) > 50:
            out.append(f"- ... {len(flags) - 50} more in metrics.json")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def write_report(out_dir: str | Path, bench: dict[str, Any]) -> dict[str, Path]:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    paths = {"report": out_dir / "benchmark_report.md", "metrics": out_dir / "metrics.json",
             "gates": out_dir / "gates.json"}
    metrics = {k: v for k, v in bench.items() if k != "gates"}
    paths["metrics"].write_text(json.dumps(jsonable(metrics), indent=1))
    paths["gates"].write_text(json.dumps(jsonable(bench["gates"]), indent=1))
    paths["report"].write_text(render(bench))
    log.info("benchmark report: %s", paths["report"])
    return paths
